### ISSUE TITLE
Launch sessions for a specific Unified API

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/vault#155]
When creating a Vault Session, make it possible to specify which Unified APIs to show. For example, for certain users, I may only want to show the CRM connectors and not the ATS.

**Comment by Gdewilde** [comment]
We added a Unified APIs field to the settings on sessions to support this. https://developers.apideck.com/apis/vault/reference#tag/Sessions

**Comment by jakeprins** [comment]
A way to implement this is just passing the API from the session settings to the connections request like `/vault/connections?api=crm`, the only problem is that it only supports scoping to a single API. So we either change the settings in the session from an array to a single value or we need to support filtering connections on multiple apis. 

We could also filter on the frontend for now. We then also need to filter during the search results so I think passing the filter directly to the endpoint will be a cleaner approach. 

@Gdewilde what do you think?

**Comment by jakeprins** [comment]
Will filter in the UI for now and added an issue for the APIs filter https://github.com/apideck-io/unify/issues/1714
