### ISSUE TITLE
Token fields 

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/vault#170]
Token fields should only show the x amount of characters + provide a reveal option to show the full token. 

<img width="1039" alt="Screenshot 2021-12-09 at 08 59 01" src="https://user-images.githubusercontent.com/1112129/145356810-b3248db2-fb78-4dd1-a000-a4ecfc80e19e.png">

**Comment by jakeprins** [comment]
note: also add to React Vault. Based on `sensitive` boolean.
