### ISSUE TITLE
Invalid Query Params for redirect URI

### ISSUE THREAD

**Issue by Kapulara** [apideck-samples/vault#197]
When URL already contains `?` the `authorizedConnection` should be added as `&authorizedConnection=...` instead of `?authorizedConnection`

![image](https://user-images.githubusercontent.com/1766076/148756005-b24fb797-5322-471c-b111-ee7ab33220da.png)

This is to align with the Query Params spec.

**Comment by jakeprins** [comment]
Thanks for reporting the issue. I'm picking this up later today🙂
