### ISSUE TITLE
Opportunities configuration for activeCampaign are not selectable

### ISSUE THREAD

**Issue by ianzone** [apideck-samples/vault#203]
![image](https://user-images.githubusercontent.com/20043230/149248700-8adf648a-cbc4-4e90-b196-bd1ec068699b.png)

When I created session with 'show_suggestions' to true, the last three fields on the image are not selectable. However, when set 'show_suggestions' to false, it works.

**Comment by jakeprins** [comment]
Sorry for the late reply.

For the Default Owner, Pipeline, and Stage fields are required to have an authorized connection. We need to make an  Active Campaign is a connector level API Key auth, so make sure the credentials being used in the connection form are correct. 

We will create a clear error message for this: https://github.com/apideck-io/unify/issues/2086
