### ISSUE TITLE
Show session invalid message on connections screen

### ISSUE THREAD

**Issue by jakeprins** [apideck-samples/vault#238]
Problems with the session still occur when creating sessions and continuing in different tabs/windows. We need to (re)implement a decent serverside session handling in hosted vault for problems like this: https://watch.screencastify.com/v/9wpxTVxcZirhUbw9fofH

`iron-session` seems like a good fit. There is an official nextjs example available: https://github.com/vercel/next.js/tree/canary/examples/with-iron-session

**Comment by Gdewilde** [comment]
Thanks for picking this up

**Comment by jakeprins** [comment]
Actually, the problem Kadonation experienced is not really related to a session bug on our side. 

They were using the `authorize_url` directly from the get connections call, but without appending a `redirect_uri` it goes back to Vault but without a JWT, so we don't have a valid session at that point. (Using the Vault UI to authorize doesn't result in any problems.)

Maybe we should update the documentation to make this clear. On the docs, there is not a mention of needing to append the `authorize_url` with a `redirect_uri` or passing a `JWT` in case they want to redirect to Vault.  

Most of the time it's probably better to redirect users to vault instead of using that `authorize_url` directly, but maybe add a description to the spec?
https://developers.apideck.com/apis/vault/reference#operation/connectionsAll

**Comment by jakeprins** [comment]
The loading screen also caused some confusion. For now, I re-named this issue and made sure we don't see that infinite loading screen but show a "Session invalid" message when there is no token provided or available.

**Comment by Gdewilde** [comment]
Ok, thanks for the clarification.
