### ISSUE TITLE
Add Unified API in search results

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/vault#242]
Services can exist across different Unified APIs. This distinction should also be visible in the search results.

<img width="1728" alt="Screenshot 2022-02-22 at 21 36 22" src="https://user-images.githubusercontent.com/1112129/155269511-8de99426-72d1-4231-8fcc-fd6558805f03.png">

**Comment by jonaslagoni** [comment]
Looks like it's already displaying the unified API during search 🙂 

![image](https://github.com/user-attachments/assets/3594cd54-1b9b-4dcd-a4fb-22b0624ac858)
