### ISSUE TITLE
Fix list of sources on Flexmail connector

### ISSUE THREAD

**Issue by jakeprins** [apideck-samples/vault#247]
"Can anybody take a look at this? I can't get a list of sources when trying to configure the Flexmail connector.
We've recently removed the possibility to receive a regular json response in favor of a HAL response. If you're expecting the regular json response then this could be the issue."

![image (1).png](https://images.zenhubusercontent.com/6017aa3c7206f157f396a24f/4232d0ac-ec1b-45ee-8d99-751d959e1b67)

**Comment by elsmr** [comment]
Fixed in unify
