### ISSUE TITLE
vault.connectionsToken is not defined

### ISSUE THREAD

**Issue by ianzone** [apideck-samples/vault#264]
![image](https://user-images.githubusercontent.com/20043230/175311349-93d957f0-4c4d-476d-810b-a1ba9d810fb7.png)

docs: https://developers.apideck.com/apis/vault/reference#operation/connectionsToken
node v18.4.0
"@apideck/node": "^2.0.0"

**Comment by jonaslagoni** [comment]
It's no longer part of the API, so should no longer be relevant :v:
