### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/vault#268]
Opening Hosted Vault in Chrome doesn't show a favicon

<img width="649" alt="Screenshot 2022-09-28 at 23 57 58" src="https://user-images.githubusercontent.com/1112129/192896282-afe908bf-04f9-4c7e-9dcb-3e7a419f09cc.png">

**Comment by jakeprins** [comment]
This is not broken. It uses the favicon that has been set on the theme settings. And if nothing is provided ithas a fallback of the Apideck logo.

Assuming the ecosystem in the screenshot is the Apideck Sandbox, the favicon is set to https://www.apideck.com/static/favicon.png, which is not a valid URL.
