### ISSUE TITLE
URL in description should not get converted to a link

### ISSUE THREAD

**Issue by jakeprins** [apideck-samples/vault#270]
Seems like ReactMarkdown auto-converts a URL to a link, which should not happen in the form field descriptions unless it's formatted as a link in markdown

![image (1)](https://user-images.githubusercontent.com/17762366/198521834-11c5b279-7495-43d8-9fe0-e3e3534a8288.png)
![image](https://user-images.githubusercontent.com/17762366/198521801-485ce223-1c49-47f7-b95d-1fcba47787ae.png)

Same for React Vault

**Comment by jonaslagoni** [comment]
With #294 it no longer seem to happen 🙂 

![image](https://github.com/user-attachments/assets/016b9e01-c888-4a84-a7d4-dc8ac2f0f46a)
