### ISSUE TITLE
Grab correct Unified API name

### ISSUE THREAD

**Issue by Gdewilde** [apideck-samples/vault#54]
<img width="1489" alt="Screenshot 2021-06-17 at 02 08 36" src="https://user-images.githubusercontent.com/1112129/122310656-0fb75980-cf11-11eb-9ddf-e7d5c1201f50.png">

**Comment by thim81** [comment]
This is corrected
![2022-10-28 at 11 35 01](https://user-images.githubusercontent.com/952446/198555752-72232b49-9bc2-40a1-804d-fb1440609340.png)
